### ISSUE TITLE
Add support for passphrase for private key to login to EC2 instance.

### ISSUE THREAD

**Issue by jainishshah17** [ArnoldZokas/grunt-ssh-multi-exec#4]
![screen shot 2014-11-24 at 12 33 36 pm](https://cloud.githubusercontent.com/assets/7799465/5172598/2a66a724-73d6-11e4-8283-9befa9ba1178.png)

**Comment by ArnoldZokas** [comment]
Added support for passphrase and published in v4.1.0 (https://www.npmjs.com/package/grunt-ssh-multi-exec).

Documented here: https://github.com/ArnoldZokas/grunt-ssh-multi-exec#private-key-with-passphrase
