### ISSUE TITLE
Async error: Callback was already called

### ISSUE THREAD

**Issue by ironblock** [ArnoldZokas/grunt-ssh-multi-exec#6]
I'm noticing this periodically on a few different machines:

```javascript
Fatal error: Callback was already called.
       Error: Callback was already called.
       at /usr/home/corey/fn10/src/gui/node_modules/grunt-ssh-multi-exec/node_modules/async/lib/async.js:30:31
       at next (/usr/home/corey/fn10/src/gui/node_modules/grunt-ssh-multi-exec/tasks/ssh-multi-exec.js:86:33)
       at /usr/home/corey/fn10/src/gui/node_modules/grunt-ssh-multi-exec/tasks/ssh-multi-exec.js:107:33
       at start-server._.assign.commands.success 
            (/usr/home/corey/fn10/src/gui/grunt_tasks/config/ssh-multi-exec.js:210:15)
       at ChannelStream.<anonymous> (/usr/home/corey/fn10/src/gui/node_modules/grunt-ssh-multi-exec/tasks/ssh-multi-exec.js:106:29)
       at ChannelStream.emit (events.js:104:17)
       at /usr/home/corey/fn10/src/gui/node_modules/grunt-ssh-multi-exec/node_modules/ssh2/lib/Channel.js:583:16
       at process._tickCallback (node.js:355:11)
```

Based on that, I think it's something to do with how `next()` is called in the `else`, when the stream closes.

Some quick googling shows similar problems where the async callback is called in an `if` and its `else`, but that doesn't seem to apply here.

I've got grunt-ssh-multi-exec triggered by the completion of a build step - we're developing on an embedded appliance, so it builds, rsyncs the app over, and then runs ssh-multi-exec to get into the box and kick the webserver service.

To that end, my code on line 210 is:

```javascript
        , { input: "/usr/sbin/service gui restart"
          , success: function( data, context, done ) {
              logSshMsg( "Issuing service restart command", "cyan" );
              printServerAddress( "starting" );
              done();
            }
          , error: function( error, context, done ) {
              printServerAddress( "YOU WERE THE CHOSEN ONE" );
              done();
            }
          }
```

The whole file is here:
https://github.com/freenas/freenas/blob/freenas10/development/src/gui/grunt_tasks/config/ssh-multi-exec.js

I'm happy to provide any other help I can. :)

**Comment by ArnoldZokas** [comment]
Hi @ironblock. This issue got lost in the github notifications :-)
I will take a look this weekend.

**Comment by ironblock** [comment]
Woohoo! Let me know if you need any help.

For what it's worth, I'm using this over a VPN some of the time - it's been almost 100% reliable while I'm on the network, but over the VPN, it happens much more frequently. I was using ssh2shell previously, but it developed other problems. If I think of anything else, I'll post it here.

**Comment by ArnoldZokas** [comment]
@ironblock i have updated dependencies and published a new package (4.2.0). I am still tracking down the leak. In the meantime, could you please upgrade to latest version and see if that helps.

**Comment by ironblock** [comment]
Awesome - I'll put a ticket on the stack for us to update our build tools, and I'll let you know what ends up happening. Our remote developers will be very happy if this fixes the problem. :)

**Comment by ironblock** [comment]
This seems to have resolved our issue - we've had no more reported errors from our remote developers. Thanks very much!

**Comment by ArnoldZokas** [comment]
That's great news!
Let me know if there's anything I can help with - I am a big fan of FreeNAS :-)
